format = """
$all$character
"""

[line_break]
disabled = true

[cmd_duration]
disabled = true

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = true
show_always = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"

# [package]
# disabled = true

[time]
disabled = true
format = '[$time]($style)'
style = "bold cyan"


# Adding Battery status to the prompt
[battery]
disabled = true
full_symbol = 'ğŸ”‹'
charging_symbol = 'âš¡ï¸'
discharging_symbol = 'ğŸ’€'
unknown_symbol = 'âš¡ï¸'
empty_symbol = 'ğŸª«'

# Force battery to show at all levels (this is key!)
[[battery.display]]
threshold = 100
style = "bold green"

[[battery.display]]
threshold = 50
style = "bold yellow"

[[battery.display]]
threshold = 20
style = "bold red"


# configure directory
[directory]
read_only = " ï ½"
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
style = "bold italic blue"

[git_branch]
symbol = "ï˜ "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
stashed = "[${count}*](green)"
modified = "[${count}+](yellow)"
deleted =  "[${count}-](red)"
conflicted =  "[${count}~](red)"
ahead = "â‡¡${count}"
behind = "â‡£${count}"
untracked = "[${count}?](blue)"
staged = "[${count}+](green)"

[git_state]
style =	"bold red"
format = "[$state( $progress_current/$progress_total) ]($style)"
rebase = "rebase"
merge = "merge"
revert = "revert"
cherry_pick = "cherry"
bisect = "bisect"
am = "am"
am_or_rebase = "am/rebase"

# [nodejs]
# # format = "via [ï¢˜ Node.js $version](bold green) "
# detect_files = ["package.json", ".node-version"]
# detect_folders = ["node_modules"]
# detect_extensions = ["js", "mjs", "cjs"]

[java]
disabled = false
symbol = "â€¢ îœ¸ "
format = '[${symbol}]($style)'
style = "fg:#a48989"

[python]
disabled = false
pyenv_version_name= false
python_binary = 'python'
format = '[${symbol}(\($virtualenv\))]($style)'
style = "fg:#a48989"
symbol = "â€¢ ó±” "

[lua]
disabled = false
symbol = "â€¢ î¨"
format = '[${symbol}]($style)'
style = "fg:#a48989"

[nodejs]
disabled = false
symbol = "â€¢ ó°™ "
format = '[${symbol} $version]($style)'
style = "fg:#a48989"
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]
detect_extensions = ["js", "mjs", "cjs"]

[package]
disabled = false
symbol = "â€¢ ï’‡ "
display_private = false
format = '[${symbol}]($style)'
style = "fg:#a48989"

[docker_context]
disabled = false
symbol = "â€¢ ïŒˆ "
only_with_files = true
format = '[${symbol}]($style)'
style = "fg:#a48989"

[golang]
disabled = false
symbol = "â€¢ î˜§ "
format = '[${symbol}]($style)'
style = "fg:#a48989"

[cpp]
disabled = false
symbol = "â€¢ î˜ "
format = '[${symbol}]($style)'
style = "fg:#a48989"

[rust]
disabled = false
symbol = "â€¢ î¨ "
format = '[${symbol}]($style)'
style = "fg:#a48989"
